@file:OptIn(androidx.compose.material3.ExperimentalMaterial3Api::class)
package com.example.musicplayer

import android.Manifest
import android.content.Intent
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.provider.Settings
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.activity.viewModels
import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.combinedClickable
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.interaction.collectIsPressedAsState
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.scale
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.core.content.ContextCompat
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.navigation.NavHostController
import androidx.navigation.compose.*
import coil.compose.AsyncImage
import com.example.musicplayer.domain.*
import com.example.musicplayer.ui.theme.AwdioTheme
import kotlin.math.max

class MainActivity : ComponentActivity() {
    private val vm: MainViewModel by viewModels { val app = application as AwdioApplication; MainViewModelFactory(app.repository, app.playbackController) }
    override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(savedInstanceState); setContent { val s by vm.uiState.collectAsStateWithLifecycle(); AwdioTheme(s.themeMode) { PermissionGate(s, vm) } } }
}

@Composable fun PermissionGate(s: MainUiState, vm: MainViewModel) { val ctx = LocalContext.current; val perm = if (Build.VERSION.SDK_INT >= 33) Manifest.permission.READ_MEDIA_AUDIO else Manifest.permission.READ_EXTERNAL_STORAGE; val launcher = rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()) { ok -> vm.permission(if (ok) LibraryPermissionState.Granted else if ((ctx as ComponentActivity).shouldShowRequestPermissionRationale(perm)) LibraryPermissionState.Denied else LibraryPermissionState.PermanentlyDenied) }; LaunchedEffect(Unit) { if (ContextCompat.checkSelfPermission(ctx, perm) == PackageManager.PERMISSION_GRANTED) vm.permission(LibraryPermissionState.Granted) else launcher.launch(perm) }; AwdioApp(s, vm, requestPermission = { launcher.launch(perm) }, openSettings = { ctx.startActivity(Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS, Uri.parse("package:${ctx.packageName}"))) }) }
@Composable fun Pressable(modifier: Modifier = Modifier, content: @Composable (Modifier) -> Unit) { val i = remember { MutableInteractionSource() }; val pressed by i.collectIsPressedAsState(); val scale by animateFloatAsState(if (pressed) .95f else 1f, label="press"); content(modifier.scale(scale)) }
@Composable fun AwdioApp(s: MainUiState, vm: MainViewModel, requestPermission:()->Unit, openSettings:()->Unit) { val nav = rememberNavController(); Scaffold(topBar = { LargeTopAppBar(title = { Text("Awdio", fontWeight = FontWeight.Bold) }, actions = { IconButton({ nav.navigate("settings") }) { Icon(Icons.Default.Settings, "Settings") }; ThemeMenu(s.themeMode, vm::theme) }) }, bottomBar = { Column { MiniPlayer(s, vm) { nav.navigate("now") }; NavigationBar(tonalElevation=8.dp) { NavItem(nav,"home",Icons.Default.LibraryMusic,"Library"); NavItem(nav,"search",Icons.Default.Search,"Search"); NavItem(nav,"playlists",Icons.Default.QueueMusic,"Playlists"); NavItem(nav,"settings",Icons.Default.Settings,"Settings") } } }) { p -> NavHost(nav, "home", Modifier.padding(p)) { composable("home") { HomeScreen(s, vm, requestPermission, openSettings) }; composable("search") { SearchScreen(s, vm, requestPermission, openSettings) }; composable("now") { NowPlayingScreen(s, vm) }; composable("playlists") { PlaylistsScreen(s, vm) }; composable("settings") { SettingsScreen(s, vm, openSettings) } } } }
@Composable fun RowScope.NavItem(nav: NavHostController, route: String, icon: androidx.compose.ui.graphics.vector.ImageVector, label: String) { val current = nav.currentBackStackEntryAsState().value?.destination?.route; NavigationBarItem(selected = current == route, onClick = { nav.navigate(route) { launchSingleTop = true; popUpTo("home") } }, icon = { Icon(icon, label) }, label = { Text(label) }) }
@Composable fun ThemeMenu(mode: ThemeMode, set: (ThemeMode)->Unit) { var open by remember { mutableStateOf(false) }; IconButton({ open = true }) { Icon(Icons.Default.Contrast, "Theme") }; DropdownMenu(open, { open = false }) { ThemeMode.entries.forEach { DropdownMenuItem(text = { Text(it.name) }, onClick = { set(it); open=false }, leadingIcon = { if (mode==it) Icon(Icons.Default.Check, null) }) } } }
@Composable fun Artwork(song: Song?, size: Int) { Surface(Modifier.size(size.dp).clip(RoundedCornerShape(20.dp)), color=MaterialTheme.colorScheme.surfaceVariant) { AsyncImage(model=song?.artworkUri, contentDescription="Album art", contentScale=ContentScale.Crop, modifier=Modifier.fillMaxSize()) } }
@OptIn(ExperimentalFoundationApi::class) @Composable fun SongRow(song: Song, liked: Boolean, onPlay:()->Unit, onFav:()->Unit, onHide:()->Unit) { var menu by remember{ mutableStateOf(false) }; ListItem(modifier = Modifier.combinedClickable(onClick=onPlay,onLongClick=onHide).fillMaxWidth(), leadingContent = { Artwork(song, 56) }, headlineContent = { Text(song.title, fontWeight = FontWeight.SemiBold) }, supportingContent = { Text("${song.artist} • ${song.album}", color=MaterialTheme.colorScheme.onSurfaceVariant) }, trailingContent = { Box { IconButton({menu=true}) { Icon(Icons.Default.MoreHoriz,"More") }; DropdownMenu(menu,{menu=false}) { DropdownMenuItem({Text(if(liked)"Unlike" else "Like")},{onFav();menu=false}, leadingIcon={Icon(Icons.Default.Favorite,null)}); DropdownMenuItem({Text("Hide from library")},{onHide();menu=false}, leadingIcon={Icon(Icons.Default.VisibilityOff,null)}) } } }) }
@Composable fun EmptyState(title:String, body:String, action:String?=null, onAction:()->Unit={}) { Column(Modifier.fillMaxSize().padding(32.dp), horizontalAlignment=Alignment.CenterHorizontally, verticalArrangement=Arrangement.Center) { Icon(Icons.Default.LibraryMusic,null,Modifier.size(52.dp), tint=MaterialTheme.colorScheme.onSurfaceVariant); Text(title, style=MaterialTheme.typography.titleLarge, fontWeight=FontWeight.Bold); Text(body, style=MaterialTheme.typography.bodyMedium, color=MaterialTheme.colorScheme.onSurfaceVariant); if(action!=null) Button(onAction, Modifier.padding(top=16.dp)){Text(action)} } }
@Composable fun LibraryContent(s:MainUiState, request:()->Unit, settings:()->Unit, content:@Composable()->Unit) { when(s.permissionState){ LibraryPermissionState.Granted -> if(s.songs.isEmpty()) EmptyState("No songs found", "Add audio files to this device and refresh your library.") else content(); LibraryPermissionState.PermanentlyDenied -> EmptyState("Permission denied", "Grant audio permission in Android settings to load your library.", "Open settings", settings); else -> EmptyState("Audio permission needed", "Awdio reads your on-device music with MediaStore.", "Grant permission", request) } }
@Composable fun HomeScreen(s: MainUiState, vm: MainViewModel, request:()->Unit, settings:()->Unit) { Column(Modifier.fillMaxSize()) { ScrollableTabRow(selectedTabIndex = s.libraryTab.ordinal) { LibraryTab.entries.forEach { Tab(selected=s.libraryTab==it,onClick={vm.tab(it)},text={Text(it.name)}) } }; LibraryContent(s,request,settings){ when(s.libraryTab){ LibraryTab.Songs -> SongList(s.songs,s,vm); LibraryTab.Albums -> GroupList(s.songs.groupBy{it.album}) { vm.play(it.first()) }; LibraryTab.Artists -> GroupList(s.songs.groupBy{it.artist}) { vm.play(it.first()) }; LibraryTab.Playlists -> PlaylistsScreen(s,vm) } } } }
@Composable fun SongList(list: List<Song>, s: MainUiState, vm: MainViewModel) { LazyColumn { items(list) { SongRow(it, it.id in s.favorites, { vm.play(it) }, { vm.favorite(it.id) }, { vm.hide(it.id) }) } } }
@Composable fun GroupList(groups: Map<String,List<Song>>, play:(List<Song>)->Unit){ LazyColumn { items(groups.keys.toList()) { key -> ElevatedCard(Modifier.padding(12.dp).fillMaxWidth()) { ListItem(headlineContent={Text(key)}, supportingContent={Text("Album · ${groups.getValue(key).size} songs · ${groups.getValue(key).first().year ?: "Unknown year"}")}, leadingContent={Artwork(groups.getValue(key).first(),56)}, trailingContent={Button({play(groups.getValue(key))}){Text("Play")}}) } } } }
@Composable fun MiniPlayer(s: MainUiState, vm: MainViewModel, expand:()->Unit) { val song=s.playback.currentSong ?: return; ElevatedCard(onClick=expand, Modifier.padding(8.dp).fillMaxWidth(), shape=RoundedCornerShape(24.dp)) { Row(Modifier.padding(10.dp), verticalAlignment=Alignment.CenterVertically) { Artwork(song,48); Spacer(Modifier.width(12.dp)); Column(Modifier.weight(1f)){ Text(song.title, fontWeight=FontWeight.SemiBold); Text(song.artist, style=MaterialTheme.typography.bodySmall) }; FilledIconButton({vm.playPause()}){Icon(if(s.playback.isPlaying) Icons.Default.Pause else Icons.Default.PlayArrow,"Play or pause") } } } }
@Composable fun Waveform(pos:Long,dur:Long){ val active = MaterialTheme.colorScheme.onSurface; val inactive = MaterialTheme.colorScheme.outlineVariant; val bars = listOf(.25f,.6f,.9f,.45f,.7f,.35f,.85f,.55f,.95f,.3f,.65f,.4f,.8f,.5f,.75f,.35f,.9f,.6f,.45f,.7f,.25f,.8f); val progress=(pos.toFloat()/max(1,dur).toFloat()).coerceIn(0f,1f); Canvas(Modifier.fillMaxWidth().height(72.dp)){ val gap=size.width/(bars.size*1.5f); bars.forEachIndexed{idx,h-> val x=idx*gap*1.5f; drawLine(if(idx.toFloat()/bars.size<=progress) active else inactive, Offset(x,size.height*(1-h)/2), Offset(x,size.height*(1+h)/2), strokeWidth=6.dp.toPx(), cap=StrokeCap.Round) } } }
@Composable fun NowPlayingScreen(s: MainUiState, vm: MainViewModel) { val song=s.playback.currentSong; Column(Modifier.fillMaxSize().padding(24.dp), horizontalAlignment=Alignment.CenterHorizontally) { Artwork(song,300); Spacer(Modifier.height(24.dp)); Row(Modifier.fillMaxWidth(), verticalAlignment=Alignment.CenterVertically){ Column(Modifier.weight(1f)){ Text(song?.title ?: "Nothing playing", style=MaterialTheme.typography.headlineMedium, fontWeight=FontWeight.Bold); Text(song?.artist ?: "Pick a song from Library", color=MaterialTheme.colorScheme.onSurfaceVariant) }; IconButton({ song?.id?.let(vm::favorite) }){Icon(Icons.Default.FavoriteBorder,"Like")}; IconButton({}){Icon(Icons.Default.MoreHoriz,"More")} }; Waveform(s.playback.positionMs,s.playback.durationMs); Row(Modifier.fillMaxWidth(), horizontalArrangement=Arrangement.SpaceBetween){Text(formatMs(s.playback.positionMs)); Text("-${formatMs((s.playback.durationMs-s.playback.positionMs).coerceAtLeast(0))}")}; Row(verticalAlignment=Alignment.CenterVertically){ IconButton({vm.shuffle()}){Icon(Icons.Default.Shuffle,"Shuffle")}; IconButton({vm.previous()}){Icon(Icons.Default.SkipPrevious,"Previous")}; FilledIconButton({vm.playPause()}, Modifier.size(72.dp), shape=CircleShape){Icon(if(s.playback.isPlaying) Icons.Default.Pause else Icons.Default.PlayArrow,"Play pause")}; IconButton({vm.next()}){Icon(Icons.Default.SkipNext,"Next")}; IconButton({vm.repeat()}){Icon(Icons.Default.Repeat,"Repeat")} }; QueueCard(s,vm) } }
fun formatMs(ms:Long)= "%d:%02d".format(ms/60000,(ms/1000)%60)
@Composable fun SearchScreen(s: MainUiState, vm: MainViewModel, request:()->Unit, settings:()->Unit) { Column(Modifier.fillMaxSize().padding(16.dp)) { OutlinedTextField(s.searchQuery, vm::search, Modifier.fillMaxWidth(), label={Text("Search songs, artists, albums")}, leadingIcon={Icon(Icons.Default.Search,null)}); Spacer(Modifier.height(12.dp)); LibraryContent(s,request,settings){ if(s.searchQuery.isBlank()) Text("Start typing to search your library.") else if(s.filteredSongs.isEmpty()) EmptyState("No results", "No songs match '${s.searchQuery}'.") else SongList(s.filteredSongs,s,vm) } } }
@Composable fun PlaylistsScreen(s: MainUiState, vm: MainViewModel) { var name by remember { mutableStateOf("") }; if(s.playlists.isEmpty()) Column(Modifier.fillMaxSize().padding(16.dp)){ Row { OutlinedTextField(name,{name=it},Modifier.weight(1f),label={Text("New playlist")}); Button({vm.createPlaylist(name);name=""}, Modifier.padding(start=8.dp)){Text("Create")} }; EmptyState("No playlists yet", "Create a playlist, then pick songs from your real library.") } else LazyColumn(Modifier.fillMaxSize().padding(12.dp)) { item { Row { OutlinedTextField(name,{name=it},Modifier.weight(1f),label={Text("New playlist")}); Button({vm.createPlaylist(name);name=""}, Modifier.padding(start=8.dp)){Text("Create")} } }; items(s.playlists) { pl -> ElevatedCard(Modifier.padding(vertical=8.dp).fillMaxWidth()) { ListItem(headlineContent={Text(pl.name)}, supportingContent={Text("${pl.songIds.size} songs")}, trailingContent={IconButton({vm.deletePlaylist(pl.id)}){Icon(Icons.Default.Delete,"Delete playlist")}}); s.songs.forEach { song -> Row(Modifier.padding(horizontal=16.dp), verticalAlignment=Alignment.CenterVertically){ Checkbox(song.id in pl.songIds,{ if(it) vm.addToPlaylist(pl.id,song.id) else vm.removeFromPlaylist(pl.id,song.id) }); Text(song.title) } } } } } }
@Composable fun SettingsScreen(s:MainUiState, vm:MainViewModel, openSettings:()->Unit){ LazyColumn(Modifier.fillMaxSize().padding(16.dp)){ item{ Text("Settings", style=MaterialTheme.typography.headlineMedium, fontWeight=FontWeight.Bold); Button(openSettings){Text("App permission settings")}; Text("Hidden songs", style=MaterialTheme.typography.titleLarge, modifier=Modifier.padding(top=20.dp)) }; if(s.blacklistedSongs.isEmpty()) item{ Text("No blacklisted songs.", color=MaterialTheme.colorScheme.onSurfaceVariant) } else items(s.blacklistedSongs){ song -> ListItem(headlineContent={Text(song.title)}, supportingContent={Text(song.artist)}, leadingContent={Artwork(song,48)}, trailingContent={TextButton({vm.restore(song.id)}){Text("Restore")}}) } } }
@Composable fun QueueCard(s: MainUiState, vm: MainViewModel) { ElevatedCard(Modifier.fillMaxWidth().padding(top=16.dp)) { Text("Up next", Modifier.padding(16.dp), style=MaterialTheme.typography.titleMedium); s.playback.queue.take(3).forEach { ListItem(headlineContent={Text(it.title)}, supportingContent={Text(it.artist)}, trailingContent={IconButton({vm.removeQueue(it.id)}){Icon(Icons.Default.Close,"Remove from queue")}}) }; Row(Modifier.padding(16.dp), verticalAlignment=Alignment.CenterVertically){ Text("Sleep timer"); Spacer(Modifier.width(8.dp)); FilterChip(s.playback.sleepTimerMinutes==15,{vm.sleep(15)},{Text("15m")}); Spacer(Modifier.width(8.dp)); FilterChip(s.playback.sleepTimerMinutes==null,{vm.sleep(null)},{Text("Off")}) } } }
